AWSTemplateFormatVersion: "2010-09-09"
Parameters:
    Linux2AMI:
        Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
        Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
        AllowedValues: 
                - '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
    MongoPassword:
        Type: String
        Default: dsuMLppftw21
Mappings:
    Template:
        UserData:
            OnBoot: |
                Content-Type: multipart/mixed; boundary="//"
                MIME-Version: 1.0

                --//
                Content-Type: text/cloud-config; charset="us-ascii"
                MIME-Version: 1.0
                Content-Transfer-Encoding: 7bit
                Content-Disposition: attachment; filename="cloud-config.txt"

                #cloud-config
                cloud_final_modules:
                - [scripts-user, always]

                --//
                Content-Type: text/x-shellscript; charset="us-ascii"
                MIME-Version: 1.0
                Content-Transfer-Encoding: 7bit
                Content-Disposition: attachment; filename="userdata.txt"
Resources:
    MongoInstance:
        Type: AWS::EC2::Instance
        Properties:
            ImageId: !Ref Linux2AMI
            InstanceType: t2.micro
            UserData:
                Fn::Base64:
                    Fn::Sub:
                        -
                            |
                            ${OnBootPrefix}
                            #!/bin/bash
                            /opt/aws/bin/cfn-init \
                                --region ${AWS::Region} \
                                -s ${AWS::StackName} \
                                -r MongoInstance \
                                -c Boot
                            --//
                        - {OnBootPrefix: !FindInMap [Template, UserData, OnBoot]}
            KeyName: sagesaver
            Tags:
                - Key: Name
                  Value: Test Mongo
                - Key: !Ref AWS::StackName
                  Value: Mongo
        Metadata:
            AWS::CloudFormation::Init:
                Init:
                    packages:
                        yum:
                            git: []
                    files:
                        /root/sagesaver/config.json:
                            content: !Sub |
                                {
                                    "aws": {
                                        "region": "${AWS::Region}",
                                        "vpc-id": "PARAMETER",
                                        "conn-str": "mongodb://admin:${MongoPassword}@localhost:27017",
                                        "stack": "${AWS::StackName}"
                                    },
                                    "autostop": {
                                        "time_limit": 1800,
                                        "db_log": {
                                            "path": "mongo.log"
                                        },
                                        "output": {
                                            "time_format": "%Y-%m-%d %H:%M:%S"
                                        }
                                    },
                                    "paths": {
                                        "sagesaver": "/root/sagesaver"
                                    }
                                }
                    commands:
                        0_SetupServerEnvironment:
                            command: !Sub |
                                git clone https://github.com/Cozieee/sagesaver sagesaver-gh
                                mv sagesaver-gh/mongo/boot/* ./sagesaver
                                bash sagesaver-gh/mongo/env/setup.sh -p ${MongoPassword}
                                rm -rf sagesaver-gh
                            cwd: /root
                Boot:
                    commands:
                        0_CheckInitialized:
                            # TODO Switch back
                            command: !Sub |
                                /opt/aws/bin/cfn-init \
                                    --region ${AWS::Region} \
                                    -s ${AWS::StackName} \
                                    -r MongoInstance \
                                    -c Init
                            test: test ! -e sagesaver
                            cwd: /root
                        1_StartCron:
                            command: bash boot.sh
                            cwd: /root/sagesaver
                configSets:
                    Init:
                        - Init
                    Boot:
                        - Boot