AWSTemplateFormatVersion: "2010-09-09"
Parameters:
    EnvironmentStack:
        Type: String
        Description: Name of the SageSaver environment stack this notebook will
            be attached to.
    NotebookName:
        Type: String
        Description: Name of the notebook
    NotebookPassword:
        Type: String
        Default: Qw3rty11
    Linux2AMI:
        Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
        Description: Don't edit this value
        Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
        AllowedValues: 
                - '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
Mappings:
    Template:
        UserData:
            OnBoot: |
                Content-Type: multipart/mixed; boundary="//"
                MIME-Version: 1.0
                --//
                Content-Type: text/cloud-config; charset="us-ascii"
                MIME-Version: 1.0
                Content-Transfer-Encoding: 7bit
                Content-Disposition: attachment; filename="cloud-config.txt"

                #cloud-config
                cloud_final_modules:
                - [scripts-user, always]

                --//
                Content-Type: text/x-shellscript; charset="us-ascii"
                MIME-Version: 1.0
                Content-Transfer-Encoding: 7bit
                Content-Disposition: attachment; filename="userdata.txt"
Resources:
    NBRole:
        Type: AWS::IAM::Role
        Properties:
            Description: Describe & Start access to DB
            Policies:
                - PolicyName: DescribeInstances
                  PolicyDocument:
                      Version: 2012-10-17
                      Statement:
                          - Effect: Allow
                            Action: ec2:DescribeInstances
                            Resource: "*"
                - PolicyName: StartDB
                  PolicyDocument:
                      Version: 2012-10-17
                      Statement:
                          - Effect: Allow
                            Action: ec2:StartInstances
                            Resource: 
                                Fn::Sub:
                                    - arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/${DatabaseID}
                                    - DBID: 
                                        Fn::ImportValue: !Sub ${EnvironmentStack}-DatabaseID

            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - ec2.amazonaws.com
                      Action:
                          - sts:AssumeRole
            Path: /SageSaver/roles/
    NBServer:
        Type: AWS::EC2::Instance
        Properties:
            ImageId: !Ref Linux2AMI
            # TODO Multiple Instance options
            InstanceType: t2.micro
            IamInstanceProfile: !Ref NBRole
            NetworkInterface:
                - AssociatePublicIpAddress: true
                  DeviceIndex: 0
                  GroupSet:
                    - Fn::ImportValue: !Sub ${EnvironmentStack}-NotebookGroupID
                  SubnetId: 
                    Fn::ImportValue: !Sub ${EnvironmentStack}-PublicSubnetID
            UserData:
                Fn::Base64:
                    Fn::Sub:
                        -
                            |
                            ${OnBootPrefix}
                            #!/bin/bash
                            /opt/aws/bin/cfn-init \
                                --region ${AWS::Region} \
                                -s ${AWS::StackName} \
                                -r NotebookInstance \
                                -c Boot
                            --//
                        - OnBootPrefix: !FindInMap [Template, UserData, OnBoot]
            KeyName: sagesaver
            Tags:
                - Key: Name
                  Value: !Sub AWS::StackName
                - Key: sagesaver:stack-origin
                  Value: !Ref NotebookName
                - Key: sagesaver:server-type
                  Value: Notebook
        Metadata:
            AWS::CloudFormation::Init:
                Init:
                    packages:
                        yum:
                            git: []
                            amazon-efs-utils: []
                    files:
                        /root/sagesaver/config.json:
                            content: 
                                Fn::Sub:
                                    - |
                                        {
                                            "aws": {
                                                "region": "${AWS::Region}",
                                                "db-id": "${DatabaseID}",
                                            },
                                            "autostop": {
                                                "time_limit": 1800,
                                                "jupyter_log": {
                                                    "path": "/home/ec2-user/jupyter.log",
                                                    "time_format": "%Y-%m-%d %H:%M:%S"
                                                },
                                                "output": {
                                                    "time_format": "%Y-%m-%d %H:%M:%S"
                                                }
                                            }
                                        }
                                    - DatabaseID:
                                        Fn::ImportValue: !Sub ${EnvironmentStack}-DatabaseID
                    commands:
                        0_SetupEFSDir:
                            command:
                                mkdir /home/ec2-user/efs
                                chmod go+rw /home/ec2-user/efs
                        1_SetupServerEnvironment:
                            command: !Sub |
                                git clone https://github.com/Cozieee/sagesaver sagesaver-gh
                                mv sagesaver-gh/notebook/boot/* ./sagesaver
                                bash sagesaver-gh/notebook/env/setup.sh -p ${NotebookPassword}
                                rm -rf sagesaver-gh
                            cwd: /root
                EFSBoilerPlate:
                    files:
                        /home/ec2-user/.env:
                            content: !Sub |
                                ENV_STACK_NAME="${EnvironmentStack}"
                    command:
                        0_LoadBoilerPlate:
                            command:
                                git clone https://github.com/Cozieee/sagesaver sagesaver-gh
                                mv sagesaver-gh/notebook/efs/* efs/
                                rm -rf sagesaver-gh
                            cwd: /home/ec2-user
                Boot:
                    commands:
                        0_CheckInitialized:
                            command: !Sub |
                                /opt/aws/bin/cfn-init \
                                    --region ${AWS::Region} \
                                    -s ${AWS::StackName} \
                                    -r NotebookInstance \
                                    -c Init
                            test: test ! -e sagesaver
                            cwd: /root
                        1_MountEFS:
                            command:
                                Fn::Sub:
                                    - mount -t efs ${EFSID} /home/ec2-user/efs
                                    - EFSID:
                                        Fn::ImportValue: !Sub ${EnvironmentStack}-EFSID
                        2_CheckEFSNotEmpty:
                            command: !Sub |
                                /opt/aws/bin/cfn-init \
                                    --region ${AWS::Region} \
                                    -s ${AWS::StackName} \
                                    -r NotebookInstance \
                                    -c EFSBoilerPlate
                            test: test -z "$(ls -A efs)"
                            cwd: /home/ec2-user
                        3_StartCron:
                            command: bash boot.sh -j /home/ec2-user/efs
                            cwd: /root/sagesaver
                configSets:
                    Init:
                        - Init
                    Boot:
                        - Boot