AWSTemplateFormatVersion: 2010-09-09
Resources:
    DBRole:
        Type: AWS::IAM::Role
        Properties:
            Description: Describe access to notebooks
            Policies:
                - PolicyName: DescribeInstances
                  PolicyDocument:
                      Version: 2012-10-17
                      Statement:
                          - Effect: Allow
                            Action: ec2:DescribeInstances
                            Resource: "*"
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - ec2.amazonaws.com
                      Action:
                          - sts:AssumeRole
            Path: /SageSaver/roles/
    NBRole:
        Type: AWS::IAM::Role
        Properties:
            Description: Describe & Start access to DB
            Policies:
                - PolicyName: DescribeInstances
                  PolicyDocument:
                      Version: 2012-10-17
                      Statement:
                          - Effect: Allow
                            Action: ec2:DescribeInstances
                            Resource: "*"
                - PolicyName: StartDB
                  PolicyDocument:
                      Version: 2012-10-17
                      Statement:
                          - Effect: Allow
                            Action: ec2:StartInstances
                            Resource: "*"
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - ec2.amazonaws.com
                      Action:
                          - sts:AssumeRole
            Path: /SageSaver/roles/
