AWSTemplateFormatVersion: 2010-09-09
Description: >
    A cheaper sagemaker-studio-like jupyter environment made for AWS new-comers
Parameters:
    DBType:
        Type: String
        Description: Type of database to host
        Default: mongo
        AllowedValues:
            - mongo
            - mysql
    DBInstanceType:
        Type: String
        Description:
            "Type of EC2 instance to launch. Recommended - Micro: testing |
            T3: Small-scale, volatile r/w | M5: Mid-Scale | R5: Large-Scale"
        Default: r5.large
        AllowedValues:
            - t2.micro
            - t3.micro
            - t3.small
            - t3.medium
            - t3.large
            - t3.xlarge
            - t3.2xlarge
            - m5.large
            - m5.xlarge
            - m5.2xlarge
            - m5.4xlarge
            - m5.8xlarge
            - r5.large
            - r5.xlarge
            - r5.2xlarge
            - r5.4xlarge
            - r5.8xlarge
    DBKeyPair:
        Type: AWS::EC2::KeyPair::KeyName
        Description: Keypair used to ssh into database
        AllowedPattern: .+
        ConstraintDescription: is required
    DBUsername:
        Type: String
        Description: Username used to connect to database
        Default: Admin
        MinLength: 1
        MaxLength: 40
        AllowedPattern: ^[a-zA-Z0-9]*$
        ConstraintDescription: has invalid length or characters
    DBPassword:
        Type: String
        Description: Password used to connect to database
        Default: dsuMLppftw21
        MinLength: 8
        MaxLength: 40
        AllowedPattern: ^[a-zA-Z0-9]*$
        ConstraintDescription: has invalid length or characters
        NoEcho: true
    DBSize:
        Type: Number
        Description: Size of the database (GB)
        Default: 20
        MinValue: 1
        ConstraintDescription: must be at least 1 GB
    DBInactiveLimit:
        Type: Number
        Description: Minutes database can be inactive (no queries) before shutting down
        Default: 30
        MinValue: 5
        MaxValue: 1440
    JournalSize:
        Type: Number
        Description: Size (GB) of EBS volume reserved for Mongo journal. 20% of data size is suggested.
        Default: 4
        MinValue: 1
        ConstraintDescription: must be at least 1 GB
    LogSize:
        Type: Number
        Description: Size (GB) of EBS volume reserved for Mongo Log. 10% of data size is suggested.
        Default: 2
        MinValue: 1
        ConstraintDescription: must be at least 1 GB
    Linux2AMI:
        Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
        Description: Image used for instances
        Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
        ConstraintDescription: cannot be changed
Conditions:
    IsMongo: !Equals [!Ref DBType, mongo]
    IsMysql: !Equals [!Ref DBType, mysql]
Metadata:
    AWS::CloudFormation::Interface:
        ParameterGroups:
            - Label:
                  default: Database
              Parameters:
                  - DBType
                  - DBInstanceType
                  - DBKeyPair
                  - DBUsername
                  - DBPassword
                  - DBSize
                  - DBInactiveLimit
            - Label:
                  default: MongoDB [IF SELECTED]
              Parameters:
                  - JournalSize
                  - LogSize
            - Label:
                  default: Enforced Configurations [DO NOT CHANGE]
              Parameters:
                  - Linux2AMI
        ParameterLabels:
            DBType:
                default: DMS Type
            DBInstanceType:
                default: EC2 Instance Type
            DBUsername:
                default: Username
            DBPassword:
                default: Password
            DBKeyPair:
                default: EC2 Key Pair
            DBSize:
                default: Storage Size
            DBInactiveLimit:
                default: Inactive Time Limit
            JournalSize:
                default: Journal Size
            LogSize:
                default: Log Size
            Linux2AMI:
                default: EC2 Instance Base AMI
Mappings:
    DBMap:
        mongo:
            Port: 27017
        mysql:
            Port: 3046
    Template:
        UserData:
            OnBoot: |
                Content-Type: multipart/mixed; boundary="//"
                MIME-Version: 1.0
                --//
                Content-Type: text/cloud-config; charset="us-ascii"
                MIME-Version: 1.0
                Content-Transfer-Encoding: 7bit
                Content-Disposition: attachment; filename="cloud-config.txt"

                #cloud-config
                cloud_final_modules:
                - [scripts-user, always]

                --//
                Content-Type: text/x-shellscript; charset="us-ascii"
                MIME-Version: 1.0
                Content-Transfer-Encoding: 7bit
                Content-Disposition: attachment; filename="userdata.txt"
Resources:
    DBInstance:
        Type: AWS::EC2::Instance
        Properties:
            ImageId: !Ref Linux2AMI
            KeyName: !Ref DBKeyPair
            InstanceType: !Ref DBInstanceType
            BlockDeviceMappings: !If
                - IsMongo
                - - DeviceName: /dev/sdf
                    Ebs:
                        VolumeType: gp3
                        VolumeSize: !Ref DBSize
                        DeleteOnTermination: true
                  - DeviceName: /dev/sdg
                    Ebs:
                        VolumeType: gp2
                        VolumeSize: !Ref JournalSize
                        DeleteOnTermination: true
                  - DeviceName: /dev/sdh
                    Ebs:
                        VolumeType: gp2
                        VolumeSize: !Ref LogSize
                        DeleteOnTermination: true
                - !If
                  - IsMysql
                  - - DeviceName: /dev/sdf
                      Ebs:
                          VolumeType: gp3
                          VolumeSize: !Ref DBSize
                          DeleteOnTermination: true
                  - AWS::NoValue
            UserData:
                Fn::Base64: !Sub
                    - |
                        ${OnBootPrefix}
                        #!/bin/bash
                        /opt/aws/bin/cfn-init \
                            --region ${AWS::Region} \
                            -s ${AWS::StackName} \
                            -r DBInstance \
                            -c Boot
                        --//
                    - OnBootPrefix: !FindInMap [Template, UserData, OnBoot]
            Tags:
                - Key: Name
                  Value: !Sub ${AWS::StackName} ${DBType}
                - Key: sagesaver:stack-origin
                  Value: !Ref AWS::StackName
                - Key: sagesaver:server-type
                  Value: Database
        Metadata:
            AWS::CloudFormation::Init:
                Init:
                    packages:
                        yum:
                            git: []
                    files:
                        /root/sagesaver/config.json:
                            content: !Sub |
                                [autostop]
                                time_limit = ${DBInactiveLimit}
                                output_log = autostop.log
                    commands:
                        0_SetupServerEnvironment:
                            command: !Sub |
                                git clone https://github.com/Cozieee/sagesaver sagesaver-gh
                                bash sagesaver-gh/envs/setup.sh -s '${DBType}' -u '${DBUsername}' -p '${DBPassword}'
                                rm -rf sagesaver-gh
                            cwd: /root
                Boot:
                    commands:
                        0_CheckInitialized:
                            command: !Sub |
                                /opt/aws/bin/cfn-init \
                                    --region ${AWS::Region} \
                                    -s ${AWS::StackName} \
                                    -r DBInstance \
                                    -c Init
                            test: test ! -e sagesaver
                            cwd: /root
                        1_StartCron:
                            command: bash boot.sh
                            cwd: /root/sagesaver
                configSets:
                    Init:
                        - Init
                    Boot:
                        - Boot
            AWS::CloudFormation::Designer:
                id: 73f4494b-b0c8-4f50-8bab-c604d1ec2a8e